jobs:
- job: windows
  pool:
    vmImage: 'windows-latest'
  steps:
    - task: Powershell@2
      displayName: 'Format C++'
      inputs:
        filePath: 'azure-pipelines/Format-CxxCode.ps1'
        pwsh: true
    - task: Powershell@2
      displayName: 'Create Diff'
      inputs:
        filePath: scripts/azure-pipelines/Create-PRDiff.ps1
        arguments: '-DiffFile $(DiffFile)'
        pwsh: true
    - task: PublishBuildArtifacts@1
      condition: failed()
      displayName: 'Publish Format and Documentation Diff'
      inputs:
        PathtoPublish: '$(DiffFile)'
        ArtifactName: 'format.diff'
